### ISSUE TITLE
Dashboard and Judge migration onto UI kit

### ISSUE THREAD

**Issue by weedkiller** [namofun/uikit#4]
Hello this is very nice, for identity, will you add support for groups and tenants.
Mongo Or grapgSql
A sample dashboard with drag drop graphs

**Comment by yang-er** [comment]
I have the plan to integrate mongo into EFCore, but not now.

And for dashboard with drag-drop, you can design it as an individual module.
I've made the route order of default `/dashboard` as 100, so you can specify a route with lower order.
Even you can add an IActionSelector to that action, which can help you decide whether to use the old-default one or newly-defined one via cookie or other things.

**Comment by yang-er** [comment]
This project is only used as the common code-base for the whole larger project. External feature requests may be rejected.
